swiftmailer:

    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }

    #transport: gmail
    #username: sedkolod71@gmail.com
   # password: 20257253
    #host: localhost
    #port: 465
    #encryption: ssl
    #auth-mode: oath
    #spool: { type: 'memory' }
    #stream_options:
     # ssl:
      #   allow_self_signed: true
       #  verify_peer: false
        # verify_peer_name: false